project/apps/tags/urls.py
from apps.tags import views
from django.urls import path

app_name = 'tags'

urlpatterns = [
    path('create/', views.TagCreateView.as_view(), name='create'),
    path('search/', views.TagSearch.as_view(), name='search')
]

project/system/urls.py
import debug_toolbar
from apps.commons.admin import site
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
                  path('admin/', site.urls),
                  path('account/', include('apps.users.urls')),
                  path('tags/', include('apps.tags.urls')),
                  path('', include('apps.pages.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
                + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

project/apps/pages/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/pages/index.css' %}">
{% endblock %}

{% block content %}
    <div class="tag-search">
        <form action="{% url 'tags:search' %}" class="tags-search-form">
            {% csrf_token %}
            <input type="text" name="search" placeholder="Поиск по тегам" class="search-input" autocomplete="off">
            <ul id="tag-search__dropdown"></ul>
        </form>
    </div>
    <div class="grid">
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/pages/index.js' %}"></script>
    <script src="{% static 'js/pages/tags.js' %}"></script>
{% endblock %}